//! `stele compile` — fan one stele.toml out to every delivery channel.
//!
//! Channels (empirical basis in conformance/RESULTS.md):
//!   .claude/settings.json      Claude Code: Stop + UserPromptSubmit hooks
//!   .codex/hooks.json          Codex CLI: same contract
//!   .devin/hooks.v1.json       Devin CLI: same contract
//!   .cursor/hooks.json         Cursor IDE (headless CLI: use `stele wrap`)
//!   .stele/hermes-shim.sh      Hermes: self-scoping global shim (+ `stele install hermes`)
//!   .git/hooks/pre-push        environment floor, fast local wall
//!   .github/workflows/stele.yml   CI: the unbypassable terminus, fail-loud
//!   AGENTS.md                  generated exhortation section (managed block)
//!
//! All writes are merge-safe and idempotent: existing user config is
//! preserved; stele-owned entries are recognized by the `stele hook` command
//! string or an explicit marker and replaced in place.

use serde_json::{json, Value};
use std::fs;
use std::path::Path;

use crate::config::Rule;

const AGENTS_BEGIN: &str = "<!-- stele:begin (generated by `stele compile`; do not edit) -->";
const AGENTS_END: &str = "<!-- stele:end -->";
const HOOK_MARKER: &str = "# stele-owned hook";

pub fn run(root: &Path, rules: &[Rule]) -> Result<Vec<String>, String> {
    let mut written = Vec::new();

    merge_claude_style(
        &root.join(".claude/settings.json"),
        "claude-code",
        true,
        &mut written,
    )?;
    merge_claude_style(&root.join(".codex/hooks.json"), "codex", false, &mut written)?;
    merge_claude_style(
        &root.join(".devin/hooks.v1.json"),
        "devin-cli",
        false,
        &mut written,
    )?;
    write_cursor(&root.join(".cursor/hooks.json"), &mut written)?;
    write_hermes_shim(root, &mut written)?;
    write_git_hook(root, &mut written)?;
    write_ci(root, &mut written)?;
    write_agents_md(root, rules, &mut written)?;

    Ok(written)
}

fn hook_cmd(harness: &str, event: &str) -> String {
    format!("stele hook {harness} {event}")
}

/// Claude Code, Codex, and Devin CLI share the hooks schema. Claude nests it
/// under a top-level "hooks" key inside settings.json; codex hooks.json uses
/// the same nesting; devin hooks.v1.json is the bare hooks object.
fn merge_claude_style(
    path: &Path,
    harness: &str,
    _nested_settings: bool,
    written: &mut Vec<String>,
) -> Result<(), String> {
    let bare = path.file_name().is_some_and(|n| n == "hooks.v1.json");
    let mut doc: Value = fs::read_to_string(path)
        .ok()
        .and_then(|t| serde_json::from_str(&t).ok())
        .unwrap_or_else(|| json!({}));

    {
        let hooks = if bare {
            &mut doc
        } else {
            if doc.get("hooks").is_none() {
                doc["hooks"] = json!({});
            }
            &mut doc["hooks"]
        };

        for (event, cmd_event) in [
            ("Stop", "stop"),
            ("UserPromptSubmit", "prompt"),
            // Guards the git layer: denies `--no-verify` while rules are red.
            ("PreToolUse", "pre-tool-use"),
        ] {
            let cmd = hook_cmd(harness, cmd_event);
            let entry = json!({
                "matcher": "",
                "hooks": [{ "type": "command", "command": cmd }]
            });
            let arr = hooks
                .as_object_mut()
                .ok_or("hooks is not an object")?
                .entry(event)
                .or_insert_with(|| json!([]));
            let arr = arr.as_array_mut().ok_or("hook event is not an array")?;
            let already = arr.iter().any(|e| {
                e["hooks"]
                    .as_array()
                    .is_some_and(|hs| hs.iter().any(|h| h["command"].as_str() == Some(&cmd)))
            });
            if !already {
                arr.push(entry);
            }
        }
    }

    write_file(path, &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()), written)
}

fn write_cursor(path: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let mut doc: Value = fs::read_to_string(path)
        .ok()
        .and_then(|t| serde_json::from_str(&t).ok())
        .unwrap_or_else(|| json!({"version": 1, "hooks": {}}));
    if doc.get("version").is_none() {
        doc["version"] = json!(1);
    }
    if doc.get("hooks").is_none() {
        doc["hooks"] = json!({});
    }
    let cmd = hook_cmd("cursor", "stop");
    let arr = doc["hooks"]
        .as_object_mut()
        .ok_or("hooks is not an object")?
        .entry("stop")
        .or_insert_with(|| json!([]));
    let arr = arr.as_array_mut().ok_or("stop is not an array")?;
    if !arr.iter().any(|e| e["command"].as_str() == Some(&cmd)) {
        arr.push(json!({"command": cmd, "timeout": 30}));
    }
    write_file(path, &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()), written)
}

/// Hermes hooks are global-only (~/.hermes/config.yaml), so the repo carries a
/// self-scoping shim; `stele install hermes` wires it globally once per user.
fn write_hermes_shim(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let shim = root.join(".stele/hermes-shim.sh");
    let body = r#"#!/usr/bin/env bash
# stele-owned hook — self-scoping Hermes shim. Hermes hooks are global-only,
# so this acts only when the session's cwd is a stele repo, else no-ops.
payload=$(cat 2>/dev/null)
cwd=$(printf '%s' "$payload" | python3 -c 'import json,sys
try: print(json.load(sys.stdin).get("cwd") or "")
except Exception: print("")' 2>/dev/null)
if [ -z "$cwd" ] || [ ! -f "$cwd/stele.toml" ]; then
  echo '{}'
  exit 0
fi
cd "$cwd" 2>/dev/null || { echo '{}'; exit 0; }
printf '%s' "$payload" | exec stele hook hermes pre_tool_call
"#;
    write_file(&shim, body, written)?;
    make_executable(&shim);
    Ok(())
}

fn write_git_hook(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let hook = root.join(".git/hooks/pre-push");
    if let Ok(existing) = fs::read_to_string(&hook) {
        if !existing.contains(HOOK_MARKER) {
            // Someone else's hook: don't clobber; the CI floor still stands.
            eprintln!(
                "stele compile: {} exists and is not stele-owned; skipped (CI still enforces)",
                hook.display()
            );
            return Ok(());
        }
    }
    let body = format!(
        "#!/usr/bin/env bash\n{HOOK_MARKER}\n\
         # Fast local wall: same check CI runs. Bypassable with --no-verify;\n\
         # CI is not.\n\
         exec stele check --quiet-green\n"
    );
    write_file(&hook, &body, written)?;
    make_executable(&hook);
    Ok(())
}

fn write_ci(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let path = root.join(".github/workflows/stele.yml");
    // Install from this repo's own origin when it has one; the env var at the
    // top is the single obvious thing to edit when publishing elsewhere.
    let origin = std::process::Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["remote", "get-url", "origin"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();
    let install = if origin.is_empty() {
        "cargo install stele --locked".to_string()
    } else {
        format!("cargo install --git ${{{{ env.STELE_SOURCE }}}} --locked")
    };
    let env_block = if origin.is_empty() {
        String::new()
    } else {
        format!("env:\n  STELE_SOURCE: {origin}\n")
    };
    let body = format!(
        r#"# Generated by `stele compile` — the unbypassable terminus.
# Fails loud on findings AND on "couldn't measure" (exit 3): a crashed
# checker must never masquerade as compliance.
name: stele
on:
  pull_request:
  push:
    branches: [main, master]
{env_block}jobs:
  stele:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install stele
        run: {install}
      - name: stele check
        run: stele check
"#
    );
    write_file(&path, &body, written)
}

fn write_agents_md(root: &Path, rules: &[Rule], written: &mut Vec<String>) -> Result<(), String> {
    let path = root.join("AGENTS.md");
    let mut section = String::new();
    section.push_str(AGENTS_BEGIN);
    section.push_str("\n## Repository rules (enforced)\n\n");
    section.push_str(
        "These rules are *measured*, not advisory: hooks block your finish, git \
         hooks block pushes, and CI blocks merges until they pass. Run `stele \
         check` any time to see where you stand.\n\n",
    );
    for rule in rules {
        section.push_str(&format!("- **{}**", rule.id));
        if !rule.description.is_empty() {
            section.push_str(&format!(": {}", rule.description));
        }
        if let Some(art) = &rule.artifact {
            section.push_str(&format!(
                " (`{}` must contain: {})",
                art.path,
                art.sections
                    .iter()
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        section.push('\n');
    }
    section.push_str(AGENTS_END);

    let existing = fs::read_to_string(&path).unwrap_or_default();
    let updated = if let (Some(start), Some(end)) =
        (existing.find(AGENTS_BEGIN), existing.find(AGENTS_END))
    {
        format!(
            "{}{}{}",
            &existing[..start],
            section,
            &existing[end + AGENTS_END.len()..]
        )
    } else if existing.is_empty() {
        format!("# Agent instructions\n\n{section}\n")
    } else {
        format!("{}\n\n{section}\n", existing.trim_end())
    };
    write_file(&path, &updated, written)
}

fn write_file(path: &Path, content: &str, written: &mut Vec<String>) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    let unchanged = fs::read_to_string(path).map(|t| t == content).unwrap_or(false);
    if !unchanged {
        fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        written.push(path.display().to_string());
    }
    Ok(())
}

fn make_executable(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = fs::metadata(path) {
            let mut perms = meta.permissions();
            perms.set_mode(perms.mode() | 0o755);
            let _ = fs::set_permissions(path, perms);
        }
    }
}

/// `stele install hermes` — patch ~/.hermes/config.yaml to point at this
/// repo's shim. Handles the `hooks: {}` stub (a naive append would create a
/// duplicate YAML key that silently loses — found the hard way).
pub fn install_hermes(root: &Path) -> Result<(), String> {
    let home = std::env::var("HOME").map_err(|_| "no $HOME")?;
    let config = Path::new(&home).join(".hermes/config.yaml");
    let shim = root.join(".stele/hermes-shim.sh");
    if !shim.is_file() {
        return Err("run `stele compile` first (no .stele/hermes-shim.sh)".into());
    }
    let text = fs::read_to_string(&config).map_err(|e| format!("{}: {e}", config.display()))?;
    let entry = format!(
        "hooks:\n  pre_tool_call:\n    - command: \"{} pre_tool_call\"\n      timeout: 60",
        shim.display()
    );
    if text.contains(&shim.display().to_string()) {
        println!("hermes already wired to this repo's shim");
        return Ok(());
    }
    let backup = config.with_extension("yaml.stele-backup");
    fs::copy(&config, &backup).map_err(|e| format!("backup: {e}"))?;
    let updated = if text.contains("\nhooks: {}\n") {
        text.replace("\nhooks: {}\n", &format!("\n{entry}\n"))
    } else if !text.lines().any(|l| l.starts_with("hooks:")) {
        format!("{}\n\n{entry}\n", text.trim_end())
    } else {
        return Err(format!(
            "~/.hermes/config.yaml already has a hooks section; add this entry manually:\n{entry}"
        ));
    };
    fs::write(&config, updated).map_err(|e| format!("{}: {e}", config.display()))?;
    println!(
        "wired hermes pre_tool_call → {} (backup at {})\nnote: consent via HERMES_ACCEPT_HOOKS=1 or `hooks_auto_accept: true`",
        shim.display(),
        backup.display()
    );
    Ok(())
}
