//! `stele compile` — fan one stele.toml out to every delivery channel.
//!
//! Channels (empirical basis in conformance/RESULTS.md):
//!   .claude/settings.json      Claude Code: Stop + UserPromptSubmit hooks
//!   .codex/hooks.json          Codex CLI: same contract
//!   .devin/hooks.v1.json       Devin CLI: same contract
//!   .cursor/hooks.json         Cursor IDE (headless CLI: use `stele run cursor`)
//!   .stele/hermes-shim.sh      Hermes: self-scoping global shim
//!   .git/hooks/pre-push        environment floor, fast local wall
//!   .github/workflows/stele.yml   CI: the unbypassable terminus, fail-loud
//!   AGENTS.md                  generated exhortation section (managed block)
//!
//! All writes are merge-safe and idempotent: existing user config is
//! preserved; stele-owned entries are recognized by the `stele hook` command
//! string or an explicit marker and replaced in place.

use serde_json::{json, Value};
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use crate::config::{self, Rule};

const AGENTS_BEGIN: &str = "<!-- stele:begin (generated by `stele compile`; do not edit) -->";
const AGENTS_END: &str = "<!-- stele:end -->";
const HOOK_MARKER: &str = "# stele-owned hook";
const STELE_REPOSITORY: &str = env!("CARGO_PKG_REPOSITORY");
const HERMES_SHIM_BODY: &str = r#"#!/usr/bin/env bash
# stele-owned hook — self-scoping Hermes shim. Hermes hooks are global-only,
# so stele self-scopes: it reads `cwd` from the payload on stdin and stays
# silent (allow) unless that directory is a git worktree with active Stele
# rules. No JSON pre-parsing here — `stele hook` does it and emits the allow.
exec stele hook hermes pre_tool_call --scope all
"#;

pub fn run(root: &Path, rules: &[Rule]) -> Result<Vec<String>, String> {
    let mut written = Vec::new();

    merge_claude_style(
        &root.join(".claude/settings.json"),
        "claude-code",
        false,
        "repo",
        &mut written,
    )?;
    merge_claude_style(
        &root.join(".codex/hooks.json"),
        "codex",
        false,
        "repo",
        &mut written,
    )?;
    merge_claude_style(
        &root.join(".devin/hooks.v1.json"),
        "devin-cli",
        true,
        "repo",
        &mut written,
    )?;
    write_cursor(&root.join(".cursor/hooks.json"), "repo", &mut written)?;
    write_hermes_shim(root, &mut written)?;
    write_git_hook(root, &mut written)?;
    write_ci(root, &mut written)?;
    write_agents_md(root, rules, &mut written)?;

    Ok(written)
}

fn hook_cmd(harness: &str, event: &str, scope: &str) -> String {
    format!("stele hook {harness} {event} --scope {scope}")
}

/// Claude Code, Codex, and Devin CLI share the hooks schema. Claude nests it
/// under a top-level "hooks" key inside settings.json; codex hooks.json uses
/// the same nesting; devin hooks.v1.json is the bare hooks object.
fn merge_claude_style(
    path: &Path,
    harness: &str,
    bare: bool,
    scope: &str,
    written: &mut Vec<String>,
) -> Result<(), String> {
    let mut doc = read_json_or(path, json!({}))?;

    {
        let hooks = if bare {
            &mut doc
        } else {
            if doc.get("hooks").is_none() {
                doc["hooks"] = json!({});
            }
            &mut doc["hooks"]
        };

        for (event, cmd_event) in [
            ("Stop", "stop"),
            ("UserPromptSubmit", "prompt"),
            ("SessionStart", "session-start"),
            // Guards the git layer: denies `--no-verify` while rules are red.
            ("PreToolUse", "pre-tool-use"),
        ] {
            let cmd = hook_cmd(harness, cmd_event, scope);
            let entry = json!({
                "matcher": "",
                "hooks": [{ "type": "command", "command": cmd }]
            });
            let arr = hooks
                .as_object_mut()
                .ok_or("hooks is not an object")?
                .entry(event)
                .or_insert_with(|| json!([]));
            let arr = arr.as_array_mut().ok_or("hook event is not an array")?;
            let owned_prefix = format!("stele hook {harness} {cmd_event}");
            let mut already = false;
            for group in arr.iter_mut() {
                if let Some(handlers) = group["hooks"].as_array_mut() {
                    handlers.retain(|handler| {
                        let Some(command) = handler["command"].as_str() else {
                            return true;
                        };
                        if !command.starts_with(&owned_prefix) {
                            return true;
                        }
                        if command == cmd && !already {
                            already = true;
                            return true;
                        }
                        false
                    });
                }
            }
            arr.retain(|group| {
                group["hooks"]
                    .as_array()
                    .is_none_or(|handlers| !handlers.is_empty())
            });
            if !already {
                arr.push(entry);
            }
        }
    }

    write_file(
        path,
        &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()),
        written,
    )
}

fn write_cursor(path: &Path, scope: &str, written: &mut Vec<String>) -> Result<(), String> {
    let mut doc = read_json_or(path, json!({"version": 1, "hooks": {}}))?;
    if doc.get("version").is_none() {
        doc["version"] = json!(1);
    }
    if doc.get("hooks").is_none() {
        doc["hooks"] = json!({});
    }
    let hooks = doc["hooks"]
        .as_object_mut()
        .ok_or("hooks is not an object")?;
    for (event, cmd_event) in [
        ("stop", "stop"),
        ("sessionStart", "session-start"),
        ("preToolUse", "pre-tool-use"),
    ] {
        let cmd = hook_cmd("cursor", cmd_event, scope);
        let owned_prefix = format!("stele hook cursor {cmd_event}");
        let arr = hooks.entry(event).or_insert_with(|| json!([]));
        let arr = arr
            .as_array_mut()
            .ok_or_else(|| format!("{event} is not an array"))?;
        let mut already = false;
        arr.retain(|entry| {
            let Some(command) = entry["command"].as_str() else {
                return true;
            };
            if !command.starts_with(&owned_prefix) {
                return true;
            }
            if command == cmd && !already {
                already = true;
                return true;
            }
            false
        });
        if !already {
            arr.push(json!({"command": cmd, "timeout": 30}));
        }
    }
    write_file(
        path,
        &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()),
        written,
    )
}

fn read_json_or(path: &Path, default: Value) -> Result<Value, String> {
    match fs::read_to_string(path) {
        Ok(text) => serde_json::from_str(&text)
            .map_err(|error| format!("{} is not valid JSON: {error}", path.display())),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(default),
        Err(error) => Err(format!("{}: {error}", path.display())),
    }
}

/// Hermes hooks are global-only (~/.hermes/config.yaml), so the repo carries a
/// self-scoping shim. `stele install global` wires the user-level copy when
/// Hermes is detected.
fn write_hermes_shim(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let shim = root.join(".stele/hermes-shim.sh");
    write_file(&shim, HERMES_SHIM_BODY, written)?;
    make_executable(&shim);
    Ok(())
}

fn write_git_hook(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let hook = root.join(".git/hooks/pre-push");
    if let Ok(existing) = fs::read_to_string(&hook) {
        if !existing.contains(HOOK_MARKER) {
            // Someone else's hook: don't clobber; the CI floor still stands.
            eprintln!(
                "stele compile: {} exists and is not stele-owned; skipped (CI still enforces)",
                hook.display()
            );
            return Ok(());
        }
    }
    let body = format!(
        "#!/usr/bin/env bash\n{HOOK_MARKER}\n\
         # Fast local wall for THIS repository's rules. Personal/system rules\n\
         # gate through their own global hooks, so they are not re-run here.\n\
         # Bypassable with --no-verify; CI is not.\n\
         exec stele check --quiet-green --scope repo\n"
    );
    write_file(&hook, &body, written)?;
    make_executable(&hook);
    Ok(())
}

fn write_ci(root: &Path, written: &mut Vec<String>) -> Result<(), String> {
    let path = root.join(".github/workflows/stele.yml");
    // Self-hosting: when this repo IS the stele source, build from the
    // checkout — works for private forks and always tests the tree under CI.
    let is_stele_source = std::fs::read_to_string(root.join("Cargo.toml"))
        .map(|t| t.contains("name = \"stele\""))
        .unwrap_or(false);
    let install = if is_stele_source {
        "cargo install --path . --locked".to_string()
    } else {
        format!("cargo install --git {STELE_REPOSITORY} --locked")
    };
    let body = format!(
        r#"# Generated by `stele compile` — the unbypassable terminus.
# Fails loud on findings AND on "couldn't measure" (exit 3): a crashed
# checker must never masquerade as compliance.
name: stele
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  stele:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install stele
        run: {install}
      - name: stele check
        run: stele check
"#
    );
    write_file(&path, &body, written)
}

fn write_agents_md(root: &Path, rules: &[Rule], written: &mut Vec<String>) -> Result<(), String> {
    let path = root.join("AGENTS.md");
    let mut section = String::new();
    section.push_str(AGENTS_BEGIN);
    section.push_str("\n## Repository rules (enforced)\n\n");
    section.push_str(
        "These rules are *measured*, not advisory: hooks block your finish, git \
         hooks block pushes, and CI blocks merges until they pass. Run `stele \
         check` any time to see where you stand.\n\n",
    );
    for rule in rules {
        section.push_str(&format!("- **{}**", rule.id));
        if !rule.description.is_empty() {
            section.push_str(&format!(": {}", rule.description));
        }
        if let Some(art) = &rule.artifact {
            section.push_str(&format!(
                " (`{}` must contain: {})",
                art.path,
                art.sections
                    .iter()
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        section.push('\n');
    }
    section.push_str(AGENTS_END);

    let existing = fs::read_to_string(&path).unwrap_or_default();
    let updated = if let (Some(start), Some(end)) =
        (existing.find(AGENTS_BEGIN), existing.find(AGENTS_END))
    {
        format!(
            "{}{}{}",
            &existing[..start],
            section,
            &existing[end + AGENTS_END.len()..]
        )
    } else if existing.is_empty() {
        format!("# Agent instructions\n\n{section}\n")
    } else {
        format!("{}\n\n{section}\n", existing.trim_end())
    };
    write_file(&path, &updated, written)
}

fn write_file(path: &Path, content: &str, written: &mut Vec<String>) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    let unchanged = fs::read_to_string(path)
        .map(|t| t == content)
        .unwrap_or(false);
    if !unchanged {
        fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        written.push(path.display().to_string());
    }
    Ok(())
}

fn make_executable(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = fs::metadata(path) {
            let mut perms = meta.permissions();
            perms.set_mode(perms.mode() | 0o755);
            let _ = fs::set_permissions(path, perms);
        }
    }
}

/// Install user-level hooks. These evaluate only system + personal rules;
/// repository-generated hooks evaluate only repository rules, so both layers
/// can coexist without duplicate findings. Hermes is included automatically
/// when ~/.hermes/config.yaml exists.
pub fn install_global() -> Result<Vec<String>, String> {
    let home = std::env::var("HOME").map_err(|_| "no $HOME")?;
    let state_dir = config::user_config_path()?
        .parent()
        .ok_or("personal config has no parent directory")?
        .to_path_buf();
    install_global_with_state(Path::new(&home), &state_dir)
}

/// Path-injectable implementation used by integration tests and managed
/// installers that stage a home directory before deployment.
pub fn install_global_at(home: &Path) -> Result<Vec<String>, String> {
    install_global_with_state(home, &home.join(".config/stele"))
}

fn install_global_with_state(home: &Path, state_dir: &Path) -> Result<Vec<String>, String> {
    // Validate every existing user file before the first write so a malformed
    // config cannot leave the multi-harness install half-applied.
    read_json_or(&home.join(".claude/settings.json"), json!({}))?;
    read_json_or(&home.join(".codex/hooks.json"), json!({}))?;
    read_json_or(
        &home.join(".cursor/hooks.json"),
        json!({"version": 1, "hooks": {}}),
    )?;
    let hermes = prepare_hermes_install(home, state_dir)?;

    let mut written = Vec::new();
    merge_claude_style(
        &home.join(".claude/settings.json"),
        "claude-code",
        false,
        "global",
        &mut written,
    )?;
    merge_claude_style(
        &home.join(".codex/hooks.json"),
        "codex",
        false,
        "global",
        &mut written,
    )?;
    write_cursor(&home.join(".cursor/hooks.json"), "global", &mut written)?;
    if let Some(update) = hermes {
        apply_hermes_install(update, &mut written)?;
    }
    Ok(written)
}

/// Compatibility entrypoint. New callers should use `stele install global`,
/// which detects and wires Hermes with every other user harness.
pub fn install_hermes() -> Result<(), String> {
    let home = std::env::var("HOME").map_err(|_| "no $HOME")?;
    let state_dir = config::user_config_path()?
        .parent()
        .ok_or("personal config has no parent directory")?
        .to_path_buf();
    install_hermes_at(Path::new(&home), &state_dir)
}

pub fn install_hermes_at(home: &Path, state_dir: &Path) -> Result<(), String> {
    let Some(update) = prepare_hermes_install(home, state_dir)? else {
        return Err(format!(
            "{} does not exist; run Hermes setup first",
            home.join(".hermes/config.yaml").display()
        ));
    };
    let mut ignored = Vec::new();
    apply_hermes_install(update, &mut ignored)
}

struct HermesInstall {
    config: PathBuf,
    shim: PathBuf,
    original: String,
    updated: String,
}

fn prepare_hermes_install(home: &Path, state_dir: &Path) -> Result<Option<HermesInstall>, String> {
    let config = home.join(".hermes/config.yaml");
    if !config.is_file() {
        return Ok(None);
    }
    let shim = state_dir.join("hermes-shim.sh");
    let original = fs::read_to_string(&config).map_err(|e| format!("{}: {e}", config.display()))?;
    let updated = install_hermes_text(&original, &shim)?;
    Ok(Some(HermesInstall {
        config,
        shim,
        original,
        updated,
    }))
}

fn apply_hermes_install(update: HermesInstall, written: &mut Vec<String>) -> Result<(), String> {
    write_file(&update.shim, HERMES_SHIM_BODY, written)?;
    make_executable(&update.shim);
    if update.original != update.updated {
        let backup = update.config.with_extension("yaml.stele-backup");
        if !backup.exists() {
            fs::copy(&update.config, &backup).map_err(|e| format!("backup: {e}"))?;
        }
        write_file(&update.config, &update.updated, written)?;
    }
    Ok(())
}

/// Remove only Stele-owned user hook entries. Personal rules are deliberately
/// retained so uninstall/reinstall is a cheap, reversible dogfooding switch.
pub fn uninstall_global() -> Result<Vec<String>, String> {
    let home = std::env::var("HOME").map_err(|_| "no $HOME")?;
    let state_dir = config::user_config_path()?
        .parent()
        .ok_or("personal config has no parent directory")?
        .to_path_buf();
    uninstall_global_with_state(Path::new(&home), &state_dir)
}

pub fn uninstall_global_at(home: &Path) -> Result<Vec<String>, String> {
    uninstall_global_with_state(home, &home.join(".config/stele"))
}

fn uninstall_global_with_state(home: &Path, state_dir: &Path) -> Result<Vec<String>, String> {
    // Parse every existing JSON document before the first mutation. An
    // uninstall must be at least as clobber-safe as the installer.
    for (path, default) in [
        (home.join(".claude/settings.json"), json!({})),
        (home.join(".codex/hooks.json"), json!({})),
        (
            home.join(".cursor/hooks.json"),
            json!({"version": 1, "hooks": {}}),
        ),
    ] {
        if path.exists() {
            read_json_or(&path, default)?;
        }
    }

    let hermes_config = home.join(".hermes/config.yaml");
    let hermes_original = if hermes_config.is_file() {
        Some(
            fs::read_to_string(&hermes_config)
                .map_err(|e| format!("{}: {e}", hermes_config.display()))?,
        )
    } else {
        None
    };

    let mut written = Vec::new();
    remove_claude_style(
        &home.join(".claude/settings.json"),
        "claude-code",
        false,
        &mut written,
    )?;
    remove_claude_style(
        &home.join(".codex/hooks.json"),
        "codex",
        false,
        &mut written,
    )?;
    remove_cursor(&home.join(".cursor/hooks.json"), &mut written)?;

    let shim = state_dir.join("hermes-shim.sh");
    if let Some(original) = hermes_original {
        let updated = uninstall_hermes_text(&original, &shim);
        if updated != original {
            let backup = hermes_config.with_extension("yaml.stele-uninstall-backup");
            fs::copy(&hermes_config, &backup).map_err(|e| format!("backup: {e}"))?;
            write_file(&hermes_config, &updated, &mut written)?;
        }
    }
    if fs::read_to_string(&shim)
        .map(|body| body.contains("stele-owned hook"))
        .unwrap_or(false)
    {
        fs::remove_file(&shim).map_err(|e| format!("{}: {e}", shim.display()))?;
        written.push(shim.display().to_string());
    }
    Ok(written)
}

fn remove_claude_style(
    path: &Path,
    harness: &str,
    bare: bool,
    written: &mut Vec<String>,
) -> Result<(), String> {
    if !path.is_file() {
        return Ok(());
    }
    let mut doc = read_json_or(path, json!({}))?;
    let mut changed = false;
    let hooks_empty;
    {
        let hooks = if bare {
            &mut doc
        } else {
            let Some(hooks) = doc.get_mut("hooks") else {
                return Ok(());
            };
            hooks
        };
        let object = hooks.as_object_mut().ok_or("hooks is not an object")?;
        let events: Vec<String> = object.keys().cloned().collect();
        for event in events {
            let Some(arr) = object.get_mut(&event).and_then(Value::as_array_mut) else {
                continue;
            };
            for group in arr.iter_mut() {
                let Some(handlers) = group.get_mut("hooks").and_then(Value::as_array_mut) else {
                    continue;
                };
                let before = handlers.len();
                let prefix = format!("stele hook {harness} ");
                handlers.retain(|handler| {
                    !handler["command"]
                        .as_str()
                        .is_some_and(|command| command.starts_with(&prefix))
                });
                changed |= handlers.len() != before;
            }
            arr.retain(|group| {
                group["hooks"]
                    .as_array()
                    .is_none_or(|handlers| !handlers.is_empty())
            });
            if arr.is_empty() {
                object.remove(&event);
            }
        }
        hooks_empty = object.is_empty();
    }
    if !changed {
        return Ok(());
    }
    if !bare && hooks_empty {
        doc.as_object_mut()
            .ok_or("settings is not an object")?
            .remove("hooks");
    }
    write_file(
        path,
        &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()),
        written,
    )
}

fn remove_cursor(path: &Path, written: &mut Vec<String>) -> Result<(), String> {
    if !path.is_file() {
        return Ok(());
    }
    let mut doc = read_json_or(path, json!({"version": 1, "hooks": {}}))?;
    let mut changed = false;
    let mut hooks_empty = false;
    if let Some(hooks) = doc.get_mut("hooks") {
        let object = hooks.as_object_mut().ok_or("hooks is not an object")?;
        let events: Vec<String> = object.keys().cloned().collect();
        for event in events {
            let Some(arr) = object.get_mut(&event).and_then(Value::as_array_mut) else {
                continue;
            };
            let before = arr.len();
            arr.retain(|entry| {
                !entry["command"]
                    .as_str()
                    .is_some_and(|command| command.starts_with("stele hook cursor "))
            });
            changed |= arr.len() != before;
            if arr.is_empty() {
                object.remove(&event);
            }
        }
        hooks_empty = object.is_empty();
    }
    if !changed {
        return Ok(());
    }
    if hooks_empty {
        doc.as_object_mut()
            .ok_or("cursor config is not an object")?
            .remove("hooks");
    }
    write_file(
        path,
        &format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()),
        written,
    )
}

fn install_hermes_text(text: &str, shim: &Path) -> Result<String, String> {
    if text.contains(&shim.display().to_string()) {
        return Ok(text.to_string());
    }
    let (migrated, replaced_old_hook) = migrate_hermes_hook(text, shim);
    if replaced_old_hook {
        return Ok(migrated);
    }

    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let trailing_newline = text.ends_with('\n');
    let entry = hermes_entry(shim);

    if let Some(index) = lines
        .iter()
        .position(|line| yaml_indent(line) == 0 && line.trim() == "hooks: {}")
    {
        lines.splice(index..=index, entry);
        return Ok(join_yaml(lines, trailing_newline));
    }

    let Some(hooks) = lines
        .iter()
        .position(|line| yaml_indent(line) == 0 && line.trim() == "hooks:")
    else {
        if lines
            .iter()
            .any(|line| yaml_indent(line) == 0 && line.trim_start().starts_with("hooks:"))
        {
            return Err("~/.hermes/config.yaml uses an unsupported inline hooks value".into());
        }
        let mut updated = text.trim_end().to_string();
        if !updated.is_empty() {
            updated.push_str("\n\n");
        }
        updated.push_str(&entry.join("\n"));
        updated.push('\n');
        return Ok(updated);
    };

    let hooks_end = yaml_section_end(&lines, hooks, 0);
    if let Some(pretool) = (hooks + 1..hooks_end).find(|&index| {
        yaml_indent(&lines[index]) == 2
            && matches!(
                lines[index].trim(),
                "pre_tool_call:" | "pre_tool_call: {}" | "pre_tool_call: []"
            )
    }) {
        if lines[pretool].trim() != "pre_tool_call:" {
            lines[pretool] = "  pre_tool_call:".to_string();
        }
        let insert = yaml_section_end(&lines, pretool, 2);
        lines.splice(insert..insert, entry.into_iter().skip(2));
    } else {
        lines.splice(hooks_end..hooks_end, entry.into_iter().skip(1));
    }
    Ok(join_yaml(lines, trailing_newline))
}

fn hermes_entry(shim: &Path) -> Vec<String> {
    let path = shim.display().to_string().replace('"', "\\\"");
    vec![
        "hooks:".to_string(),
        "  pre_tool_call:".to_string(),
        format!("    - command: \"{path} pre_tool_call\""),
        "      timeout: 60".to_string(),
    ]
}

fn uninstall_hermes_text(text: &str, shim: &Path) -> String {
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let trailing_newline = text.ends_with('\n');
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim_start();
        if trimmed.starts_with("- command:") && owned_hermes_command(&lines[index], shim) {
            let indent = yaml_indent(&lines[index]);
            let mut end = index + 1;
            while end < lines.len() {
                let candidate = &lines[end];
                if !candidate.trim().is_empty() && yaml_indent(candidate) <= indent {
                    break;
                }
                end += 1;
            }
            lines.drain(index..end);
            continue;
        }
        index += 1;
    }

    // Clean up a now-empty Stele-created pre_tool_call section, then the
    // containing hooks section. Unrelated hook entries and comments survive.
    if let Some(hooks) = lines
        .iter()
        .position(|line| yaml_indent(line) == 0 && line.trim() == "hooks:")
    {
        let hooks_end = yaml_section_end(&lines, hooks, 0);
        if let Some(pretool) = (hooks + 1..hooks_end)
            .find(|&i| yaml_indent(&lines[i]) == 2 && lines[i].trim() == "pre_tool_call:")
        {
            let pretool_end = yaml_section_end(&lines, pretool, 2);
            if lines[pretool + 1..pretool_end]
                .iter()
                .all(|line| line.trim().is_empty())
            {
                lines.drain(pretool..pretool_end);
            }
        }
        let hooks_end = yaml_section_end(&lines, hooks, 0);
        if lines[hooks + 1..hooks_end]
            .iter()
            .all(|line| line.trim().is_empty())
        {
            lines.splice(hooks..hooks_end, ["hooks: {}".to_string()]);
        }
    }
    join_yaml(lines, trailing_newline)
}

fn owned_hermes_command(line: &str, shim: &Path) -> bool {
    line.contains(&shim.display().to_string())
        || line.contains("stele hook hermes pre_tool_call")
        || line.contains(".stele/hermes-shim.sh")
        || line.contains("/stele/hermes-shim.sh")
        || line.contains("personal-stele/hermes-shim.sh")
}

fn yaml_indent(line: &str) -> usize {
    line.len() - line.trim_start_matches(' ').len()
}

fn yaml_section_end(lines: &[String], start: usize, indent: usize) -> usize {
    (start + 1..lines.len())
        .find(|&index| {
            let line = lines[index].trim();
            !line.is_empty() && !line.starts_with('#') && yaml_indent(&lines[index]) <= indent
        })
        .unwrap_or(lines.len())
}

fn join_yaml(lines: Vec<String>, trailing_newline: bool) -> String {
    let mut text = lines.join("\n");
    if trailing_newline || !text.is_empty() {
        text.push('\n');
    }
    text
}

fn migrate_hermes_hook(text: &str, shim: &Path) -> (String, bool) {
    let mut replaced = false;
    let mut lines = Vec::new();
    for line in text.lines() {
        let old_stele_hook = owned_hermes_command(line, shim);
        if line.trim_start().starts_with("- command:") && old_stele_hook {
            let indent = &line[..line.len() - line.trim_start().len()];
            lines.push(format!(
                "{indent}- command: \"{} pre_tool_call\"",
                shim.display()
            ));
            replaced = true;
        } else {
            lines.push(line.to_string());
        }
    }
    let mut updated = lines.join("\n");
    if text.ends_with('\n') {
        updated.push('\n');
    }
    (updated, replaced)
}
